### ISSUE TITLE
Improve validation for names

### ISSUE THREAD

**Issue by andrevenancio** [devcon-london/website#12]
I kind of take offense when people say I can't write special characters. my name has special characters....  any reason we can't allow that?

**Comment by andrevenancio** [comment]
I can write ven`â`ncio but I can't write andr`é`.. maybe we need to improve the regexp

**Comment by grudelsud** [comment]
yeah, have a look at this https://stackoverflow.com/questions/280712/javascript-unicode-regexes

**Comment by grudelsud** [comment]
we need to consider:
- unicode characters
- apostrophes
- names made of more than 2 elements
