### ISSUE TITLE
send users a notification email when submission gets accepted

### ISSUE THREAD

**Issue by grudelsud** [devcon-london/website#15]
this will be particularly relevant for new members

also at the moment, there's no way to add them to slack and google groups

**Comment by grudelsud** [comment]
exploring https://sendgrid.com/pricing/
should be straight forward with a firestore function, e.g. [this](https://medium.com/google-cloud/sendgrid-email-automation-with-google-firestore-functions-30afcf7ac7aa)

**Comment by silviopaganini** [comment]
https://github.com/firebase/functions-samples/tree/master/quickstarts/email-users

**Comment by andrevenancio** [comment]
I would be keen on keeping this all in one platform. firebase seems to be pretty decent. If there's costs at some point, they are all contained within one platform

**Comment by grudelsud** [comment]
> I would be keen on keeping this all in one platform. firebase seems to be pretty decent. If there's costs at some point, they are all contained within one platform

firebase doesn't send emails

**Comment by lusocoding** [comment]
Send grid is a great solution for this particular use case and pricing is not to worry for a long time since it allows one hundred emails per day on the free plan.

**Comment by silviopaganini** [comment]
in progress #52
