### ISSUE TITLE
Propose renaming of the git repo to devcon-website

### ISSUE THREAD

**Issue by chrisbarry** [devcon-london/website#18]
I suggest this repo gets renamed to devcon-website, as "website" is a little tricky to identify in a big folder of projects...

Unless the expectation is that people would just do this themselves after they clone, so perhaps that is fine.

**Comment by andrevenancio** [comment]
you can rename the folder you clone this to?

**Comment by lusocoding** [comment]
passing the desired folder name during the git clone command will suffice no?
