### ISSUE TITLE
Automatic Deployments

### ISSUE THREAD

**Issue by andrevenancio** [devcon-london/website#2]
I assume we're going to move forward with `git flow` and if that's the case we could probably automate the deployments when a version is released and merged into master.

Tagging you @grudelsud as the assignee since I suspect either you or @silviopaganini will have the final say on the server.

**Comment by grudelsud** [comment]
oh yes, continuous integration is probably step 3246 and we're still at n. 3, but totally agree with you. re. hosting, I see these possible options at the moment, all free or very cheap, and need to assess functionalities (e.g. ssl for custom domain, api for deployment, etc. etc.)

- github pages (as the static website we have at the moment)
- hosting on firebase
- netlify
- s3 bucket with custom domain
- appengine

would like to hear feedback from the team

**Comment by andrevenancio** [comment]
any will do, but if we can go with Github pages then we cut our dependencies short as we have everything in one place, but I'm really happy with whatever.

**Comment by grudelsud** [comment]
1st release of the website, deploy is as manual as it can be 😂 as GH pages and the new website are physically in 2 different repos, so it goes like the following

```
cd website
npm run build
cd ../devcon-london.github.io
cp -a ../website/build/* .
git commit -a -m "new release"
git push
```

**Comment by silviopaganini** [comment]
yeye done
