### ISSUE TITLE
new members mechanics

### ISSUE THREAD

**Issue by andrevenancio** [devcon-london/website#28]
I think its a good idea that all members are linked to a current member. if this is an invite only community.

with that in mind we must adopt a invite mechanism like invite code or some unique url to link new members to a actual member. i think down the line this will be an interesting visualisation on how the community got put together.

at the moment anyone can sign up, which isnt in line with the guidelines on the homepage

**Comment by grudelsud** [comment]
just to be entirely clear on this, at the moment anybody can authenticate (with GH) and, if not a member, submit a request to join. This is then reviewed by an admin and either accepted or rejected.

There are many ways to improve the process, most of them involving some decisions and subsequent development. E.g. one improvement in the registration flow could be what discussed in #15 

There's a trade-off we need to set between being formal and informal, flexible and strict, open to growth or private. This threshold is probably moving as we go along and learn from the process. At the end of the day, there are ~250 users on Slack, with probably ~50 being really active, and that reflects on how many decided to take the leap and make the submission on the new website.

one for discussion.
