### ISSUE TITLE
Invite members automatically to Slack

### ISSUE THREAD

**Issue by silviopaganini** [devcon-london/website#38]
Once member is approved

**Comment by grudelsud** [comment]
yeah, I planned to do it a while ago, before realising that Slack doesn't allow it with the free API

I started writing a few scripts to reconcile users (in the script folder) but unfortunately, the API to add users to a workspace is only for paid clients, here: https://api.slack.com/scim while the free API doesn't have such functionality https://api.slack.com/methods

**Comment by silviopaganini** [comment]
see #52 added a method to invite to Slack automatically
