### ISSUE TITLE
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by drydenwilliams** [devcon-london/website#46]
I've signed in successfully with Github but when I go to the "Subscribe" tab I get the following error:

```
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
``` 

<img width="983" alt="Screenshot 2019-09-25 at 06 30 48" src="https://user-images.githubusercontent.com/4403089/65571857-10020b00-df5e-11e9-9651-417a0851de48.png">

--- 

Browser: Chrome 76
OS: OS X 10.14.6

**Comment by grudelsud** [comment]
hey @drydenwilliams I'm having a hard time reproducing this bug. 

I've created a new `bugfix/permissions` branch with the commit you see above here, with the only purpose to have some console logs and see where it raises. Would you mind running the website locally (just plain `SKIP_PREFLIGHT_CHECK=true npm run start`) and share what you see in console? your uid should come out as well, useful to check what's in the database.

something like this should show up:

<img width="528" alt="Screenshot 2019-11-15 at 16 58 34" src="https://user-images.githubusercontent.com/310976/68962469-91428500-07cc-11ea-8141-365512fc410c.png">

sorry && thanks

@silviopaganini any other ideas on how to check this? I should delete my membership to test it properly, or have another github account, both of them quite painful options.

**Comment by silviopaganini** [comment]
I think 1) ... it's painful but still easier than creating a new GH account

**Comment by grudelsud** [comment]
I've ended up creating a new GH dev account so I can do the full run both locally and remotely, whilst being able to delete my data and start from scratch again. I think I found the bug, I'm on it.
