### ISSUE TITLE
Sign in on devcon.network

### ISSUE THREAD

**Issue by silviopaganini** [devcon-london/website#57]
need to update the domain for the signin

can we keep both for now?

**Comment by grudelsud** [comment]
<img width="521" alt="Screenshot 2020-01-03 at 11 46 36" src="https://user-images.githubusercontent.com/310976/71721862-b9d71a80-2e1e-11ea-87fa-888dda967148.png">

done

**Comment by grudelsud** [comment]
also updated the redirect from devcon.london
